language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
